name: Rust

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install JACK or PipeWire JACK
      run: |
        sudo apt-get update
        # Try to install JACK2, fallback to PipeWire JACK if needed
        sudo apt-get install -y pipewire-jack libpipewire-0.3-jack || sudo apt-get install -y libjack-jackd2-dev 

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
